server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: D:/Promtail/positions.yaml
clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push


scrape_configs:
  - job_name: app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: app-logs
          __path__: D:/GitHub/BankAPI/app.log  # Укажите путь к файлу логов вашего приложения
